version: "3.8"

services:
  mongodb:
    image: mongo:6

  backend:
    image: migcoin-backend:latest
    build: ./backend
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cloud_app_db
      - PORT=3000
    depends_on:
      - mongodb

  frontend:
    image: migcoin-frontend:latest
    build:
      context: ./MigcoinApplication
      dockerfile: Dockerfile
    depends_on:
      - backend
