services:
  mongodb:
    image: mongo:6
    container_name: mongodb_container
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - /data/mongo:/data/db

  backend:
    build: ./backend
    container_name: node_backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/cloud_app_db
    depends_on:
      - mongodb

  frontend:
    build: ./AngularApp
    container_name: angular_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
