# For more information on how to configure your workflow, see the documentation: https://docs.github.com/actions/learn-github-actions/workflow-syntax-for-github-actions
name: Build & Push Docker Images

on:
  push:
    branches:
      - localhost

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Backend Image
        run: |
          docker build -t siddhu101010/migcoin-backend:latest ./backend
          docker push siddhu101010/migcoin-backend:latest

      - name: Build & Push Frontend Image
        run: |
          docker build -t siddhu101010/migcoin-frontend:latest ./MigcoinApplication
          docker push siddhu101010/migcoin-frontend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd AngularApp
            docker compose pull
            docker compose up -d
            